baseURL = 'https://husnaram.site/'
languageCode = 'en-us'
title = 'Husnaram'
theme = "anubis2"

[author]
name = "Husna Ramadan"

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[menus]
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 10
